### ISSUE TITLE
Add support for field domains

### ISSUE THREAD

**Issue by dmfenton** [Esri/koop-agol#26]
For example: The field secondTier in this dataset has coded values.
http://s1-mdc.cloud.eaglegis.co.nz/arcgis/rest/services/Data/OpenData/MapServer/19?f=pjson

- Downloads that don't support domains: decode on the fly
- Downloads that do support domains (e.g. gpkg, fgdb) create constraint table
- When serving feature services include domain information in field metadata

**Comment by chelm** [comment]
supported in koop now
