### ISSUE TITLE
fix "callback is already called"

### ISSUE THREAD

**Issue by chelm** [Esri/koop-agol#29]
request workers  are erroring out when pages of data fail more than once. We are seeing this error in the logs: 

if (called) throw new Error("Callback was already called.");

It has something to do with the way the `catchErrors` method is re-adding the task to the async queue

**Comment by ngoldman** [comment]
This is tangential to the issue, but... is Koop using [exponential backoff](http://en.wikipedia.org/wiki/Exponential_backoff) for handling retries? i.e. retry in 2, 4, 8, 16, 32, 64, 128.

**Comment by chelm** [comment]
@ngoldman its not. The flow is that if a request fails on the first try it placed at the end of the queue and is retried 3 times until it will fail the job and mark the dataset as failed. 

It'd be super simple to add in exponential backoffs though. There is a retry counter (counts to 3 tries) and koop could add a delay to each request based on the retry count.

this issue relates to something I thought I was able to fix by sending anon functions as the callbacks, but that is not the case. Somewhere my callbacks are being called a second time.

**Comment by chelm** [comment]
Some info worth understanding: https://github.com/caolan/async/issues/614

**Comment by chelm** [comment]
So for now I'm catching the error and preventing this from killing jobs. Whats going on is that some requests are failing twice causing two callbacks to fire. I'll need more time to re-work some of the error logic before we prevent this from happening but in the meantime we can fail gracefully.
